### ISSUE TITLE
[FEAT] DEVICE CRUD

### ISSUE THREAD

**Issue by hannahf97** [posco3-2/userService-server#4]
## 💡 Issue
단말정보에 관한 CRUD 를 생성 

## 📝 todo
- [ ] device create
- [ ] device update
- [ ] device delete
- [ ] device get all 
- [ ] device get web
- [ ] device get app
